# Generated by Django 5.2.9 on 2025-12-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_image',
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='district_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='district_ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='address_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='address_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='condition_en',
            field=models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('needs_repair', 'Needs repair')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='condition_ru',
            field=models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('needs_repair', 'Needs repair')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type_en',
            field=models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('land', 'Участок'), ('commercial', 'Коммерческая недвижимость')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type_ru',
            field=models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('land', 'Участок'), ('commercial', 'Коммерческая недвижимость')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_en',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_ru',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('land', 'Участок'), ('commercial', 'Коммерческая недвижимость')], max_length=20),
        ),
    ]
