# Generated by Django 5.2.9 on 2025-12-26 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0002_remove_city_city_image_city_city_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_type_en',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_type_ru',
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='house_app.city'),
        ),
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='house_app.district'),
        ),
    ]
