# Generated by Django 5.2.9 on 2025-12-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0003_remove_property_property_type_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='condition_en',
        ),
        migrations.RemoveField(
            model_name='property',
            name='condition_ru',
        ),
    ]
